### ISSUE TITLE
"Crafting" condition goes back to "Default" between crafting steps

### ISSUE THREAD

**Issue by KuroZantetsuken** [Aida-Enna/GraphicsConfig#3]
Looking at the Dalamud Condition Data, doing a crafting action applies condition ID 40 "Crafting40" which disappears when the action is completed, leaving only ID 5 "Crafting", but the plugin goes to the "Default" configuration when ID 40 disappears.

**Comment by Aida-Enna** [comment]
Fixed in https://github.com/Aida-Enna/GraphicsConfig/commit/52fa5db0aff28d6828ccf1dc03d3e6020a395761, thanks again 👍
