### ISSUE TITLE
Ability to (optionally?) also save Display Settings

### ISSUE THREAD

**Issue by fifi-ch** [Aida-Enna/GraphicsConfig#4]
Hey absolutely in love this plogon, just the sauce I needed, except for one tiny thing.

Could there be an option added to also save Display Settings? Which Screen Mode, resolution, frame rate etc.

This would be super sweet to quickly switch between a "main" preset with full graphics and fullscreen and a "side" preset set up to go smol window on the side with lowest settings.

**Comment by Aida-Enna** [comment]
I can definitely take a look, it should be _theoretically_ possible unless the game does something funky with that stuff (which is possible since everyone will have different resoutions and frame rates, but we'll see)

**Comment by Aida-Enna** [comment]
Good news and bad news:

Good news ✔️ - I can (and did, https://github.com/Aida-Enna/GraphicsConfig/commit/5e42c79425bfb6c667da40aee553b622d467ec33) definitely add support for these in the plugin, and changing the FPS is instantly applied.

Bad news ❌ - Screen Mode (Windowed/Borderless/Fullscreen) and Resolution (Width/Height) do not get applied when you change them, only when you open the config window, change something on any property, then hit apply. This makes sense considering how it works when you manually click it. Unfortunately, automating it to hit apply would bring in a lot of separate issues and an amount of work equal to a rewrite. Sorry :c

**Comment by fifi-ch** [comment]
Absolutely reasonable, thank you for trying and looking into it!
